FROM python:3.11

COPY requirements.txt /tmp/

# Upgrade pip to the latest version and install the Python dependencies
RUN pip install --upgrade pip && pip install -r /tmp/requirements.txt

COPY trips_manager.py /opt/

WORKDIR /opt/

CMD ["python3", "trips_manager.py"]